#ifndef ALLCOINGURU_CHAINPARAMSSEEDS_H
#define ALLCOINGURU_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the allcoinguru network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x05,0x2d,0x4f,0x3c}, 8881}
};

static SeedSpec6 pnSeed6_test[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x05,0x2d,0x4f,0x3c}, 16787}
};
#endif // ALLCOINGURU_CHAINPARAMSSEEDS_H
